parameters:
    app.formato_fecha: 'd/m/Y H:i'

services:
    _defaults:
        autowire: true      
        autoconfigure: true 
        bind:
            $formato: '%app.formato_fecha%'

    App\:
        resource: '../src/'
